version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: MPeru123@
      MYSQL_DATABASE: cliente_persona_db
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    image: cliente-persona:1.0
    container_name: cliente-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cliente_persona_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MPeru123@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge